[package]
name = "openstream-media"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors = ["OpenStream contributors"]

[dependencies]
lowlat-audio.workspace = true
lowlat-core.workspace = true
openstream-protocol = { path = "../protocol" }
openstream-transport = { path = "../transport" }

[lints]
workspace = true
